site_name: LearnDataEngineering
site_description: Personal Notes on Data Science, Analytics & Data Engineering
site_author: Akshay MP

theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: amber
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - content.code.copy
    - content.action.edit
    - content.action.view

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md

  - Data Science:
      - Python: DataScience/python.md
      - Statistics: DataScience/statistics.md
      - Machine Learning (ML): DataScience/machine-learning.md

  - Analytics:
      - SQL: Analytics/sql.md
      - Microsoft Power BI: Analytics/power-bi.md

  - Data Engineering:
      - DE Cycle: DataEngineering/de-cycle.md
      - Application Programming Interface: DataEngineering/api.md
      - Networking Basics: DataEngineering/networking.md
      - PySpark:
          - Overview: DataEngineering/pyspark.md
          - Databricks Practical Guide: DataEngineering/pyspark/databricks-practical-guide.md

  - DataBricks: 
      - Table of Contents: DataBricks/introduction.md
  - Cloud:
      - Introduction: Cloud/introduction.md
      - AWS: Cloud/aws_notes.md
      - Azure: Cloud/azure_notes.md
      - GCP: Cloud/gcp_notes.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
